### ISSUE TITLE
[Question]: How Can I Set Custom Header with Rule Environment

### ISSUE THREAD

**Issue by fatihusta** [octarinesec/ModSecurity-envoy#3]
Hi
I'm using modsecurity-envoy.
I'm trying set a header after rule action like below. But doesn't work. I'm not sure, Is this modsecurity issue or modsecurity-envoy issue or this configuration isn't right?

Rules
```
SecRule ARGS:json.isbn  "4545454" "id:4,phase:2,deny,status:400,setenv:ACTION=Blocked,msg:'Test JSON rule'"
Header set X-Action "%{ACTION}e" env=ACTION
```

Logs
```
[2019-09-11 07:38:12.912][23535][error][filter] [http-filter-modsecurity/http_filter.cc:36] Failed to load rules: Rules error. File: /root/ModSecurity-envoy/conf/modsecurity.conf. Line: 16. Column: 42. Invalid input:  Header set X-Action "%{ACTION}e" env=ACTION
```

**Comment by yoshpe** [comment]
This action is not yet supported by libmodsecurity (see [here](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#setenv)).
You can tell it's an issue with modsecurity because the error is that the rule is not recognized.

Having said that, in the case that libmodsecurity will support setting headers, we will also have to add the support for it in this bridge.

**Comment by fatihusta** [comment]
thanks @yoshpe
